<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Applied Missing data analysis with SPSS and R(Studio)</title>
  <meta name="description" content="Applied Missing data analysis with SPSS and R(Studio)">
  <meta name="generator" content="bookdown 0.7 and GitBook 2.6.7">

  <meta property="og:title" content="Applied Missing data analysis with SPSS and R(Studio)" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Applied Missing data analysis with SPSS and R(Studio)" />
  
  
  

<meta name="author" content="Martijn Heymans and Iris Eekhout">


<meta name="date" content="2018-09-04">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="index.html">
<link rel="next" href="references.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Applied Missing Data Analysis</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#the-goal-of-this-manual"><i class="fa fa-check"></i><b>0.1</b> The goal of this Manual</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#multiple-imputation-in-spss-and-r"><i class="fa fa-check"></i><b>0.2</b> Multiple Imputation in SPSS and R</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#notation-and-annotation-in-this-manual"><i class="fa fa-check"></i><b>0.3</b> Notation and annotation in this manual</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="software-applications.html"><a href="software-applications.html"><i class="fa fa-check"></i><b>1</b> Software applications</a><ul>
<li class="chapter" data-level="1.1" data-path="software-applications.html"><a href="software-applications.html#spss-data-and-variable-view-windows"><i class="fa fa-check"></i><b>1.1</b> SPSS, Data and Variable View windows</a></li>
<li class="chapter" data-level="1.2" data-path="software-applications.html"><a href="software-applications.html#analyzing-data-in-spss"><i class="fa fa-check"></i><b>1.2</b> Analyzing data in SPSS</a></li>
<li class="chapter" data-level="1.3" data-path="software-applications.html"><a href="software-applications.html#data-transformations-in-spss"><i class="fa fa-check"></i><b>1.3</b> Data Transformations in SPSS</a></li>
<li class="chapter" data-level="1.4" data-path="software-applications.html"><a href="software-applications.html#the-output-window-in-spss"><i class="fa fa-check"></i><b>1.4</b> The Output window in SPSS</a></li>
<li class="chapter" data-level="1.5" data-path="software-applications.html"><a href="software-applications.html#the-syntax-editor-in-spss"><i class="fa fa-check"></i><b>1.5</b> The Syntax Editor in SPSS</a></li>
<li class="chapter" data-level="1.6" data-path="software-applications.html"><a href="software-applications.html#reading-and-saving-data-in-spss"><i class="fa fa-check"></i><b>1.6</b> Reading and saving data in SPSS</a></li>
<li class="chapter" data-level="1.7" data-path="software-applications.html"><a href="software-applications.html#r-and-rstudio"><i class="fa fa-check"></i><b>1.7</b> R and RStudio</a><ul>
<li class="chapter" data-level="1.7.1" data-path="software-applications.html"><a href="software-applications.html#the-role-of-the-console-window"><i class="fa fa-check"></i><b>1.7.1</b> The role of the Console Window</a></li>
<li class="chapter" data-level="1.7.2" data-path="software-applications.html"><a href="software-applications.html#r-assignments-and-objects"><i class="fa fa-check"></i><b>1.7.2</b> R assignments and objects</a></li>
<li class="chapter" data-level="1.7.3" data-path="software-applications.html"><a href="software-applications.html#vectors-matrices-lists-and-data-frames"><i class="fa fa-check"></i><b>1.7.3</b> Vectors, matrices, lists and data frames</a></li>
<li class="chapter" data-level="1.7.4" data-path="software-applications.html"><a href="software-applications.html#indexing-vectors-matrices-lists-and-data-frames"><i class="fa fa-check"></i><b>1.7.4</b> Indexing Vectors, Matrices, Lists and Data frames</a></li>
<li class="chapter" data-level="1.7.5" data-path="software-applications.html"><a href="software-applications.html#vectorized-calculation"><i class="fa fa-check"></i><b>1.7.5</b> Vectorized Calculation</a></li>
<li class="chapter" data-level="1.7.6" data-path="software-applications.html"><a href="software-applications.html#r-functions"><i class="fa fa-check"></i><b>1.7.6</b> R Functions</a></li>
<li class="chapter" data-level="1.7.7" data-path="software-applications.html"><a href="software-applications.html#the-help-function"><i class="fa fa-check"></i><b>1.7.7</b> The Help function</a></li>
<li class="chapter" data-level="1.7.8" data-path="software-applications.html"><a href="software-applications.html#working-with-script-files"><i class="fa fa-check"></i><b>1.7.8</b> Working with script files</a></li>
<li class="chapter" data-level="1.7.9" data-path="software-applications.html"><a href="software-applications.html#creating-a-working-directory"><i class="fa fa-check"></i><b>1.7.9</b> Creating a working directory</a></li>
<li class="chapter" data-level="1.7.10" data-path="software-applications.html"><a href="software-applications.html#reading-in-spss-data-in-rstudio"><i class="fa fa-check"></i><b>1.7.10</b> Reading in SPSS data in RStudio</a></li>
<li class="chapter" data-level="1.7.11" data-path="software-applications.html"><a href="software-applications.html#saving-and-reading-r-data-in-rstudio"><i class="fa fa-check"></i><b>1.7.11</b> Saving and Reading R data in RStudio</a></li>
<li class="chapter" data-level="1.7.12" data-path="software-applications.html"><a href="software-applications.html#reading-in-rstudio-data-into-spss"><i class="fa fa-check"></i><b>1.7.12</b> Reading in (R)Studio data into SPSS</a></li>
<li class="chapter" data-level="1.7.13" data-path="software-applications.html"><a href="software-applications.html#installing-r-packages"><i class="fa fa-check"></i><b>1.7.13</b> Installing R Packages</a></li>
<li class="chapter" data-level="1.7.14" data-path="software-applications.html"><a href="software-applications.html#loading-r-packages"><i class="fa fa-check"></i><b>1.7.14</b> Loading R Packages</a></li>
<li class="chapter" data-level="1.7.15" data-path="software-applications.html"><a href="software-applications.html#updating-r-packages"><i class="fa fa-check"></i><b>1.7.15</b> Updating R Packages</a></li>
<li class="chapter" data-level="1.7.16" data-path="software-applications.html"><a href="software-applications.html#useful-missing-data-packages-and-links"><i class="fa fa-check"></i><b>1.7.16</b> Useful Missing data Packages and links</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Applied Missing data analysis with SPSS and R(Studio)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="software-applications" class="section level1">
<h1><span class="header-section-number">Chapter 1</span> Software applications</h1>
<p>Statistical software programs can help us to analyze our data. SPSS and R are such programs. Although SPSS and R are among the most popular programs to do statistical data analyses nowadays, they do not have much in common. One of the greatest differences is that SPSS works with menu options that make windows appear and you can click buttons to select options, whereas R works with lines of code that you have to type in to run analyses. This makes SPSS more user-friendly than R for applied researchers. In SPSS you are overloaded with output tables, and in R you only get output on demand. In this Chapter we will explore the different possibilities of the SPSS (IBM 2016) and the R software language (Matloff, 2011, Dalgaard, 2008). We will run R via RStudio, the integrated development environment (IDE) for R. RStudio includes a wide range of productivity enhancing features, which makes it easier to work with than with the R console on its own.</p>
<div id="spss-data-and-variable-view-windows" class="section level2">
<h2><span class="header-section-number">1.1</span> SPSS, Data and Variable View windows</h2>
<p>In this manual we work with SPSS version 24 (IBM, 2016). When you start SPSS Version 24 a start-up window appears. In this window, you can directly open the files that were active during your previous use of SPSS. These files can be found and easily opened in the “Recent files” window (Figure <a href="software-applications.html#fig:fig1">1.1</a>). If you do not want to see this window the next time that you open SPSS, select “Don’t show this dialog in the future”.</p>
<div class="figure" style="text-align: center"><span id="fig:fig1"></span>
<img src="images/fig1.1.png" alt="First window after you have started SPSS" width="90%" />
<p class="caption">
Figure 1.1: First window after you have started SPSS
</p>
</div>
<p>When you click on Close on the right side below, the window will close and you will see an empty Data View window. Now you are in the SPSS Data Editor window. This window is always open when you start SPSS. The name “SPSS Data Editor” is also visible at the top of the screen and is called “IBM SPSS Statistics Data Editor” (Figure <a href="software-applications.html#fig:fig2">1.2</a>).</p>
<div class="figure" style="text-align: center"><span id="fig:fig2"></span>
<img src="images/fig1.2.png" alt="Data View window in SPSS" width="90%" />
<p class="caption">
Figure 1.2: Data View window in SPSS
</p>
</div>
<p>In the SPSS Data Editor, you have the possibility to go to the Data View and Variable View windows. In the Data View window, you can enter data yourself or read in data by using the options in the file menu. In Figure 1.2 you see an example of a dataset in the Data View window. Each row in the Data View window represents a case and in the columns you will find the variable names. In the Data View window, you can do all kind of data manipulations by using the different menu’s above in the window. From here you can click on the tab Variable View, in the lower left corner of the window. Than the Variable view window will appear (Figure <a href="software-applications.html#fig:fig3">1.3</a>).</p>
<div class="figure" style="text-align: center"><span id="fig:fig3"></span>
<img src="images/fig1.3.png" alt="Variable View window in SPSS" width="90%" />
<p class="caption">
Figure 1.3: Variable View window in SPSS
</p>
</div>
<p>In the Variable View window, you can add new variables, by entering the name in the name column. Further, you can change the columns by using the following options: Type: Here you can change the type of variables in your dataset. Mostly you work with numeric variables, i.e. a variable whose values are numbers. Other possibilities are Date variables which is a numeric variable whose values are displayed in one of several calendar-date or clock-time formats or String variables, a character (text) variable that can contain any characters up to the defined length. String values are not numeric and therefore are not used in calculations. Width: By default SPSS defines a numeric variable with 8 digits for each new variable.</p>
<p>Decimals: the number of decimal places displayed.</p>
<p>Label: The variable name.</p>
<p>Values: To assign numbers to the categories of a variable. To define Variable values do the following: 1. Click the button in the Values cell for the variable that you want to define. 2. For each value, enter the value and a label. 3. Click Add to enter the value label. 4. Click OK.</p>
<p>Missing: Here you can define specified data values as user-missing. You can enter up to three discrete (individual) missing values, a range of missing values, or a range plus one discrete value.</p>
<p>Columns: To change the number of characters displayed in the Data View window.</p>
<p>Align: Here you can specify the alignment of your data.</p>
<p>Measure: Here you can specify the level of each variable, scale (continuous), ordinal or nominal.</p>
<p>Role: Here you can define the role of the variable during your analysis. Examples are, Input for independent variable, Target for dependent or outcome variable, Both, independent and dependent variable. There are more possibilities, but most of the times you use the default Input setting.</p>
</div>
<div id="analyzing-data-in-spss" class="section level2">
<h2><span class="header-section-number">1.2</span> Analyzing data in SPSS</h2>
<p>All statistical procedures in SPSS can be found under the Analyze button (Figure <a href="software-applications.html#fig:fig4">1.4</a>). Here you also will find the option “Multiple Imputation” which plays an important role in this manual. We will use this menu later on in Chapter 4.</p>
<div class="figure" style="text-align: center"><span id="fig:fig4"></span>
<img src="images/fig1.4.png" alt="Statistical procedures that can be found under the Analyze menu in SPSS" width="90%" />
<p class="caption">
Figure 1.4: Statistical procedures that can be found under the Analyze menu in SPSS
</p>
</div>
</div>
<div id="data-transformations-in-spss" class="section level2">
<h2><span class="header-section-number">1.3</span> Data Transformations in SPSS</h2>
<p>Two other interesting buttons are Data and Transform. The Data menu allows you to make changes to the data editor. Here you can add new variables or cases. You can also use the Split File option, to get analyses results separately for categories of a variable. The Transform menu allows you to manipulate your variables by for example dichotomizing a numeric variable.</p>
</div>
<div id="the-output-window-in-spss" class="section level2">
<h2><span class="header-section-number">1.4</span> The Output window in SPSS</h2>
<p>If you have run your analyses in SPSS, an SPSS Output (or viewer) Window will pop-up. The main body of the Output Window consists of two panes (left and right panes). In the left pane you will find an outline of the output. In the right pane you will find the actual output of your statistical procedure (Figure <a href="software-applications.html#fig:fig5">1.5</a>).</p>
<div class="figure" style="text-align: center"><span id="fig:fig5"></span>
<img src="images/fig1.5.png" alt="Part of the Output or Viewer window in SPSS after making use of Descriptive Statistics under the Analyze menu" width="90%" />
<p class="caption">
Figure 1.5: Part of the Output or Viewer window in SPSS after making use of Descriptive Statistics under the Analyze menu
</p>
</div>
</div>
<div id="the-syntax-editor-in-spss" class="section level2">
<h2><span class="header-section-number">1.5</span> The Syntax Editor in SPSS</h2>
<p>In the syntax editor of SPSS, you use the SPSS syntax programming language. You can run all SPSS procedures by typing in commands in this syntax editor window, instead of using the graphical user interface, i.e. by using your mouse and clicking on the menu´s. You can get access to the syntax window in two ways. The first is just by opening a new syntax file by navigating to File -&gt; New -&gt; Syntax. This will open a new syntax window (Figure <a href="software-applications.html#fig:fig6">1.6</a>).</p>
<div class="figure" style="text-align: center"><span id="fig:fig6"></span>
<img src="images/fig1.6.png" alt="Screenshot of new syntax file" width="90%" />
<p class="caption">
Figure 1.6: Screenshot of new syntax file
</p>
</div>
<p>Now you can start writing your syntax directly in this window. You can also generate syntax by accessing statistical procedures through the dropdown menus and clicking the Paste button instead of clicking the OK button after you have specified the options. When you have clicked the Paste button, a new Syntax Editor window will pop up or the new syntax will automatically be added to the open Syntax Editor window. This is a very useful way to keep track of the analysis that you have performed. An example can be found in Figure <a href="software-applications.html#fig:fig7">1.7</a>, where the syntax is shown for the Descriptive Statistics procedure of Figure <a href="software-applications.html#fig:fig5">1.5</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:fig7"></span>
<img src="images/fig1.7.png" alt="Screenshot of Syntax editor of SPSS including the Syntax code for descriptive statisitcs" width="90%" />
<p class="caption">
Figure 1.7: Screenshot of Syntax editor of SPSS including the Syntax code for descriptive statisitcs
</p>
</div>
<p>By using the SPSS Syntax it is possible for users to perform the same analyses over and over again or to adapt the analysis via the syntax code for complex calculations in the data. In this manual we will not use SPSS syntax code to access statistical procedures, however we recommend to use the SPSS syntax to keep track of the analysis that you have performed. SPSS is most frequently used via the graphical user interface, and we will use that method also in this manual.</p>
</div>
<div id="reading-and-saving-data-in-spss" class="section level2">
<h2><span class="header-section-number">1.6</span> Reading and saving data in SPSS</h2>
<p>Reading in data in SPSS is very easy; via the menu File choose for File -&gt; Open -&gt; Data. All kind of file types can be selected. Of course the SPSS .sav files, but also .por, .xlsx, .cvs, SAS, Stata, etc. (Figure 1.8). After you have selected a specific file type you may have to go through several steps before you see the data in the Data View window. These steps are not necessary for SPSS files, they open directly in the data editor.</p>
<div class="figure" style="text-align: center"><span id="fig:fig8"></span>
<img src="images/fig1.8.png" alt="Window to read in different file types in SPSS" width="90%" />
<p class="caption">
Figure 1.8: Window to read in different file types in SPSS
</p>
</div>
<p>Saving files in SPSS is possible via the Save Data As option under the menu File. You can choose the same kind of file types (Figure <a href="software-applications.html#fig:fig9">1.9</a>).</p>
<div class="figure" style="text-align: center"><span id="fig:fig9"></span>
<img src="images/fig1.9.png" alt="Option Save Data As under the menu File" width="90%" />
<p class="caption">
Figure 1.9: Option Save Data As under the menu File
</p>
</div>
</div>
<div id="r-and-rstudio" class="section level2">
<h2><span class="header-section-number">1.7</span> R and RStudio</h2>
<p>RStudio is an integrated environment to work with the software program R. Consequently, to work with RStudio, R has to be installed. RStudio uses the R language and is also freely available. In this manual we will only show some possibilities and options in RStudio that are needed to run the R code and the programs that are discussed in this manual. For more information about RStudio and its possibilities visit the RStudio website at www.rstudio.com. When you open RStudio the following screen will appear.</p>
<div class="figure" style="text-align: center"><span id="fig:fig10"></span>
<img src="images/fig1.10.png" alt="First screen that appears after you have started RStudio" width="90%" />
<p class="caption">
Figure 1.10: First screen that appears after you have started RStudio
</p>
</div>
<p>There are three windows opened:</p>
<ol style="list-style-type: decimal">
<li>On the left is the Console window</li>
</ol>
<p>This is the main window to run R code (see below for more information about the Console window).</p>
<ol start="2" style="list-style-type: decimal">
<li>Right above is the window where you can choose between the Environment and History tabs (e.g. history tracks the code you typed in the Console window).</li>
<li>At the right site below is the window where you can choose between Files, Plots, Packages, Help and Viewer tabs.</li>
</ol>
<div id="the-role-of-the-console-window" class="section level3">
<h3><span class="header-section-number">1.7.1</span> The role of the Console Window</h3>
<p>When you enter code in the Console window you will directly receive a result. For example, you can type the following code and the result will appear directly in the Console window.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">3</span> <span class="op">+</span><span class="st"> </span><span class="dv">3</span></code></pre></div>
<pre><code>## [1] 6</code></pre>
<p>As you can see, you can use R as a large calculator. Other multiplication procedures as divide, square, etc. can also be executed. However, the main use for R is its functions. For example, when you generate 20 random numbers you can use the following function code (we will discuss more about functions in R later):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rnorm</span>(<span class="dv">20</span>)</code></pre></div>
<pre><code>##  [1] -0.83691133 -1.02270611  1.20870988  0.59442366  0.20538960
##  [6] -1.85271464 -0.69006987 -1.17203002 -1.02228044 -0.67901954
## [11] -0.98024791  0.81072035 -0.04646819 -1.52278600  1.38214866
## [16] -0.10384478 -0.56257695 -1.23565133  3.20518398  0.92787693</code></pre>
<p>The number [1] between brackets is the index of the first number or item in the vector. That can be useful when you have many numbers printed in the Console window.</p>
</div>
<div id="r-assignments-and-objects" class="section level3">
<h3><span class="header-section-number">1.7.2</span> R assignments and objects</h3>
<p>In R it is possible to create objects and to assign values to these objects. In this way it is for example possible to store some intermediate results and recall or use them later on. Assigning values to objects is done by using the assignment operator &lt;- (R code below). You can also use the = sign as an assignment operator. This is not recommended because this is also a symbol used for some mathematical operations. For example, when we want to assign the value 3 to the object x, we use the following code.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="dv">3</span> </code></pre></div>
<p>When we subsequently type in the letter x we get the following result:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x </code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>As result we see the value 3 again. Now the value 3 is assigned to the object x. In R all kind of information can be assigned to an object, i.e. one number, a vector of numbers, results from analysis or other R objects such as data frames, matrices or lists. Objects can have all kinds of different names, composed of different letters and numbers. Here are some examples where number 3 is assigned to different objects with different names:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">test &lt;-<span class="st"> </span><span class="dv">3</span>
test.<span class="dv">1</span> &lt;-<span class="st"> </span><span class="dv">3</span>
test.manual &lt;-<span class="st"> </span><span class="dv">3</span>
test</code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">test.<span class="dv">1</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">test.manual </code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>Note that some letters and words are used by R itself. It is not recommended to use these leters as names for objects in R that you create yourself. For example, the letter T and F are used as TRUE and FALSE by R. Other letters that are already in use are c, q, t, C, D, I and diff, df, and pt.</p>
</div>
<div id="vectors-matrices-lists-and-data-frames" class="section level3">
<h3><span class="header-section-number">1.7.3</span> Vectors, matrices, lists and data frames</h3>
<p><em>Vectors</em> In the previous paragraph we created the one-vector x, i.e. a vector that contained only one number, the number 3. Mostly you do your analysis on more numbers than just one. R has several possibilities to create objects with more data. We start with a simple dataset, called a data vector, which is an array of numbers (such as created in R code 1.2. A vector can be created by the following code:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>)
y</code></pre></div>
<pre><code>## [1] 1 2 3 4 5</code></pre>
<p>Now the numbers 1, 2, 3, 4 and 5 are assigned to the data vector y. The “c” in the above code stand for concatenate which makes that all separate (one-vector) numbers are merged into one vector. It is also possible to create character vectors, which are vectors that contain strings (text). An example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;a&quot;</span>, <span class="st">&quot;b&quot;</span>, <span class="st">&quot;test&quot;</span>)
y</code></pre></div>
<pre><code>## [1] &quot;a&quot;    &quot;b&quot;    &quot;test&quot;</code></pre>
<p>Vectors can also be made by using the “:” symbol. With that symbol it is easy to generate a sequence of numbers. An example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">10</span>
y</code></pre></div>
<pre><code>##  [1]  1  2  3  4  5  6  7  8  9 10</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="dv">2</span><span class="op">:</span><span class="dv">6</span>
y</code></pre></div>
<pre><code>## [1] 2 3 4 5 6</code></pre>
<p>Both lines of code produce a vector containing a sequence of numbers. The first example produces the numbers 1 to 10 and the second example the numbers 2 to 6.</p>
<p><em>Matrix</em> A matrix in R contains rows and columns and can be created by using the matrix function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>), <span class="dt">nrow=</span><span class="dv">2</span>, <span class="dt">ncol=</span><span class="dv">3</span>)</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    3    5
## [2,]    2    4    6</code></pre>
<p>Now we have created a matrix with 2 rows and 3 columns. In essence we converted the vector c(1, 2, 3, 4, 5, 6) into a matrix.</p>
<p><em>List</em> Another popular R object class is a list. The advantage of a list is that it can contain components of different formats. Let’s look at an example using the following code:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">5</span>
x</code></pre></div>
<pre><code>## [1] 1 2 3 4 5</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;a&quot;</span>, <span class="st">&quot;b&quot;</span>, <span class="st">&quot;test&quot;</span>)
z &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dt">x=</span>x, <span class="dt">y=</span>y)
z</code></pre></div>
<pre><code>## $x
## [1] 1 2 3 4 5
## 
## $y
## [1] &quot;a&quot;    &quot;b&quot;    &quot;test&quot;</code></pre>
<p>The code created the list object z consisting of the two components x and y which are the vectors that were created above. You can see that in a list two components of different data type can be combined, a numeric and a character factor. The names of the list components are indicated by the dollar sign, <span class="math inline">\(. The list component can be obtained separately by typing z\)</span>x for component x or x$y for component y.</p>
<p><em>Dataframe</em> Mostly we work with datasets that contain information of different variables and persons. In R such a dataset is called a dataframe. In essence, a dataframe in R is a list, where each component of the list is a vector of equal length. This example code first creates a list, consisting of 3 vectors of the same length. Than this list is converted into a dataframe, using the data.frame function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">k &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dt">a=</span><span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, <span class="dt">b=</span><span class="dv">11</span><span class="op">:</span><span class="dv">20</span>, <span class="dt">c=</span><span class="dv">21</span><span class="op">:</span><span class="dv">30</span>)
k</code></pre></div>
<pre><code>## $a
##  [1]  1  2  3  4  5  6  7  8  9 10
## 
## $b
##  [1] 11 12 13 14 15 16 17 18 19 20
## 
## $c
##  [1] 21 22 23 24 25 26 27 28 29 30</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">z &lt;-<span class="st"> </span><span class="kw">data.frame</span>(k)
z</code></pre></div>
<pre><code>##     a  b  c
## 1   1 11 21
## 2   2 12 22
## 3   3 13 23
## 4   4 14 24
## 5   5 15 25
## 6   6 16 26
## 7   7 17 27
## 8   8 18 28
## 9   9 19 29
## 10 10 20 30</code></pre>
<p>Typically, a dataframe is created by reading in an existing dataset. How to create a dataframe by reading in a dataset will be further discussed in the paragraph “Reading in and saving data”.</p>
</div>
<div id="indexing-vectors-matrices-lists-and-data-frames" class="section level3">
<h3><span class="header-section-number">1.7.4</span> Indexing Vectors, Matrices, Lists and Data frames</h3>
<p><em>Vectors</em> An important operation in R is to select a subset of a given vector. This is called indexing vectors. This subset of the vector elements can be assigned to another vector. An example how to do this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">8</span>, <span class="dv">5</span>, <span class="dv">4</span>, <span class="dv">8</span>, <span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">6</span>)
y[<span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">4</span>)]</code></pre></div>
<pre><code>## [1] 3 8</code></pre>
<p>The R code y[c(1, 4)], extracts the first and fourth element of the vector. Another example is by using the “:” symbol, to extract several subsequent elements:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y[<span class="dv">2</span><span class="op">:</span><span class="dv">5</span>]</code></pre></div>
<pre><code>## [1] 5 2 8 5</code></pre>
<p>The R code y[2:5], extracts the second to the fifth element of the vector.</p>
<p>A minus sign excludes the specific element from the vector, like:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y[<span class="op">-</span><span class="dv">3</span>]</code></pre></div>
<pre><code>## [1] 3 5 8 5 4 8 1 3 6</code></pre>
<p>The R code y[-3], excludes the third element of the vector (i.e. 2). A new vector z can be created where the third and fourth element of the y vector are excluded, by using the following code:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">z &lt;-<span class="st"> </span>y[<span class="op">-</span><span class="kw">c</span>(<span class="dv">3</span>, <span class="dv">4</span>)]
z</code></pre></div>
<pre><code>## [1] 3 5 5 4 8 1 3 6</code></pre>
<p><em>Matrices</em> When we index matrices we can choose to index rows, columns or both. Here are some examples:</p>
<p>First we construct the matrix</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">z &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">9</span>, <span class="dt">nrow=</span><span class="dv">3</span>)
z</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    4    7
## [2,]    2    5    8
## [3,]    3    6    9</code></pre>
<p>We extract from the first row the number in the second column</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">z[<span class="dv">1</span>, <span class="dv">2</span>]</code></pre></div>
<pre><code>## [1] 4</code></pre>
<p>We extract all numbers in each column in the first row</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">z[<span class="dv">1</span>, ]</code></pre></div>
<pre><code>## [1] 1 4 7</code></pre>
<p>We extract all numbers in each row of the first column</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">z[, <span class="dv">1</span>]</code></pre></div>
<pre><code>## [1] 1 2 3</code></pre>
<p>A minus sign can also be used to delete specific elements or complete rows or columns.</p>
<p>Omit the first row from the matrix</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">z[<span class="op">-</span><span class="dv">1</span>, ]</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    2    5    8
## [2,]    3    6    9</code></pre>
<p><em>Lists</em> We first create a list with 3 components, each component consists of a vector of the same length and with 10 elements each.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">k &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dt">a=</span><span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, <span class="dt">b=</span><span class="dv">11</span><span class="op">:</span><span class="dv">20</span>, <span class="dt">c=</span><span class="dv">21</span><span class="op">:</span><span class="dv">30</span>)
k</code></pre></div>
<pre><code>## $a
##  [1]  1  2  3  4  5  6  7  8  9 10
## 
## $b
##  [1] 11 12 13 14 15 16 17 18 19 20
## 
## $c
##  [1] 21 22 23 24 25 26 27 28 29 30</code></pre>
<p>There are several options to index list components and elements of the components. If we want to index the individual component b we can use the following code:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">k<span class="op">$</span>b</code></pre></div>
<pre><code>##  [1] 11 12 13 14 15 16 17 18 19 20</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">k[[<span class="st">&quot;b&quot;</span>]]</code></pre></div>
<pre><code>##  [1] 11 12 13 14 15 16 17 18 19 20</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">k[[<span class="dv">2</span>]]</code></pre></div>
<pre><code>##  [1] 11 12 13 14 15 16 17 18 19 20</code></pre>
<p>As you have may noticed, to extract individual list components double square brackets are used, compared to single brackets for indexing vectors and matrices.</p>
<p>When we use single brackets, we get the following results:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">k[<span class="st">&quot;b&quot;</span>]</code></pre></div>
<pre><code>## $b
##  [1] 11 12 13 14 15 16 17 18 19 20</code></pre>
<p>The difference between using single and double brackets is that single brackets return the component data type, which is in this case a vector (but could be any kind of data type) and single brackets always return a list.</p>
<p><em>Data frames</em> Indexing data frames follows the same method as indexing matrices, but we can also use the method that is used to index lists, since data frames are essentially lists of vectors of the same length. Data frames consist of rows and columns which can be accessed separately or both to extract specific elements. We use the data frame that was constructed in R code 1.11.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">z</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    4    7
## [2,]    2    5    8
## [3,]    3    6    9</code></pre>
<p>Examples of indexing the first column are:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">z[, <span class="dv">1</span>]</code></pre></div>
<pre><code>## [1] 1 2 3</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">k<span class="op">$</span>a</code></pre></div>
<pre><code>##  [1]  1  2  3  4  5  6  7  8  9 10</code></pre>
<p>The second row can be accessed by using:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">z[<span class="dv">2</span>, ]</code></pre></div>
<pre><code>## [1] 2 5 8</code></pre>
</div>
<div id="vectorized-calculation" class="section level3">
<h3><span class="header-section-number">1.7.5</span> Vectorized Calculation</h3>
<p>An advantage of working with R is that it is possible to perform vectorized calculations. This means that you can do calculations elementwise, i.e. the same calculation is done on each element of an object. Let’s look at an example.</p>
<p>We first create a vector z with numerical variables.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">z &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>)
z</code></pre></div>
<pre><code>## [1] 1 2 3 4 5 6 7 8</code></pre>
<p>Now it is fairly easy to square each element of the vector by typing:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">z<span class="op">^</span><span class="dv">2</span></code></pre></div>
<pre><code>## [1]  1  4  9 16 25 36 49 64</code></pre>
<p>The ^2 means take the power of 2. We see that each element is squared. These vectorized calculations can be done by using all kinds of mathematical functions, e.g. taking the square root, logarithms, adding constant values to each element, etc.</p>
</div>
<div id="r-functions" class="section level3">
<h3><span class="header-section-number">1.7.6</span> R Functions</h3>
<p>Functions play an important role in R. Functions can be seen as lines of R code to run all kind of data procedures and to return a result. Let’s write a small function that we name “sum.test” that generates a sequence of numbers from 1 to 5 and sums all values from 1 to the value we define beforehand, which is in our example the value 3. This means that the function will sum all values from 1 to 3, i.e. 1 + 2 + 3 when it is at the value of 3 and all values from 1 to 4 when we use as input value the value 4. The function can be found in R code 1.26.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">print.sum.test &lt;-<span class="st"> </span><span class="cf">function</span>(x) 
{
 <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">5</span>) 
 {
   <span class="cf">if</span> (i<span class="op">==</span>x) y &lt;-<span class="st"> </span><span class="kw">sum</span>(<span class="dv">1</span><span class="op">:</span>i)  
 }
<span class="kw">return</span>(y)
}
<span class="kw">print.sum.test</span>(<span class="dv">3</span>)</code></pre></div>
<pre><code>## [1] 6</code></pre>
<p>At the first line we define the function print.sum.test that includes one argument x. Than in de body of the function (in italic) which starts with a left brace and ends with another brace, the actual calculations take place. The return statement gives back the result. At the end we call the function with the statement print.sum.test(3), where the value 3 is actually used in the function.</p>
<p>Once the function is defined, we can call the function and plug in other values. For example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print.sum.test</span>(<span class="dv">4</span>)</code></pre></div>
<pre><code>## [1] 10</code></pre>
<p>That will directly lead to the result 10 when the value 4 is used.</p>
<p>You can write functions yourself but in R many functions are available which means that many calculations are done by using function calls. A function name is followed by a set of parentheses which contain some arguments. In the above self-written function, we already made use of a function, which is the sum function. We can use it separately as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(<span class="dv">3</span>,<span class="dv">4</span>)</code></pre></div>
<pre><code>## [1] 7</code></pre>
<p>The arguments in this function are the numbers 3 and 4 and the result is their sum. This function uses as arguments numbers or complete vectors. If you want to see the formal arguments of each function you can use the args function. You have to type the name of the function as the argument in the args function. For example, we can use it for the matrix function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">args</span>(matrix)</code></pre></div>
<pre><code>## function (data = NA, nrow = 1, ncol = 1, byrow = FALSE, dimnames = NULL) 
## NULL</code></pre>
<p>As a result the arguments of the functions are listed with their default settings. In this case the arguments are:</p>
<p>data: an optional data vector (including a list or expression vector).</p>
<p>nrow: the desired number of rows.</p>
<p>ncol: the desired number of columns.</p>
<p>byrow: logical. If FALSE (the default) the matrix is filled by columns, otherwise the matrix is filled by rows.</p>
<p>dimnames: A dimnames attribute for the matrix: NULL or a list of length 2 giving the row and column names respectively. An empty list is treated as NULL, and a list of length one as row names. The list can be named, and the list names will be used as names for the dimensions.</p>
</div>
<div id="the-help-function" class="section level3">
<h3><span class="header-section-number">1.7.7</span> The Help function</h3>
<p>There are several possibilities to start the help facilities in R and to get more information about functions and their arguments in R.</p>
<p>You can just type help or use the question mark as follows:</p>
<p>help(matrix) ?matrix</p>
<p>In both ways the help tutorial for the matrix function will be activated and appear in your web browser or in help tab in the right corner below when you use R studio.</p>
</div>
<div id="working-with-script-files" class="section level3">
<h3><span class="header-section-number">1.7.8</span> Working with script files</h3>
<p>If you want to use R code and functions more than once it is useful to work with scripts files. In this way you can type and save R code and reuse it. To create a script file in R is easy.</p>
<p>After you have started RStudio you go to File -&gt; New File -&gt; R Scripts. Now a new window will open on the left side above. In that file you can type for example the self-written function print.sum.test. (Figure <a href="software-applications.html#fig:fig11">1.11</a>). Now you can save the script file by using the Save option under the File menu, open it again and use it whenever you want.</p>
<div class="figure" style="text-align: center"><span id="fig:fig11"></span>
<img src="images/fig1.11.png" alt="Script file example in RStudio" width="90%" />
<p class="caption">
Figure 1.11: Script file example in RStudio
</p>
</div>
</div>
<div id="creating-a-working-directory" class="section level3">
<h3><span class="header-section-number">1.7.9</span> Creating a working directory</h3>
<p>It is a good idea to keep your R files at the same place when you are doing data analysis for some kind of project. If you do not use a separate directory, R will use a default directory, that will mostly be in Windows in the documents folder. All files that you have to use during your R session are assumed to be in that directory. Further, all files that you save during your session will be in that directory. To locate your working directory, you can type in the Console window:</p>
<p>If you want to change your working directory to for example C:(Note that the path in R uses forward slashes and the path in Windows backward slashes!), you can type:</p>
<p>In Rstudio there is another way to get information about the current working directory and another way to change the working directory. Go in RStudio to the window on the right site below and go to the Files tab and click on the right site of the screen on the three dots. Than a window will open and you can browse to your preferred folder. Then choose for More in the Files tab and then select “Set As Working Directory” (Figure <a href="software-applications.html#fig:fig12">1.12</a>). Now you have set your preferred working directory. You can check if your directory is set correctly by choosing “Go To Working Directory”.</p>
<div class="figure" style="text-align: center"><span id="fig:fig12"></span>
<img src="images/fig1.12.png" alt="Working directory selection in RStudio" width="90%" />
<p class="caption">
Figure 1.12: Working directory selection in RStudio
</p>
</div>
</div>
<div id="reading-in-spss-data-in-rstudio" class="section level3">
<h3><span class="header-section-number">1.7.10</span> Reading in SPSS data in RStudio</h3>
<p>There are several procedures in RStudio to read in datasets.</p>
<ol style="list-style-type: decimal">
<li>Import datasets via “Import Dataset” An easy way to do that is via the window at the right site above. There you will find the button which is called “Import Dataset”. When you click on it you can choose between different kind of file types, i.e. CVS, Excel, SPSS, SAS and Stata files (Figure 1.13).</li>
</ol>
<div class="figure" style="text-align: center"><span id="fig:fig13"></span>
<img src="images/fig1.13.png" alt="Screen to import datasets in RStudio" width="90%" />
<p class="caption">
Figure 1.13: Screen to import datasets in RStudio
</p>
</div>
<p>In this example we choose for SPSS. When you approach this procedure for the first time it could be that RStudio asks for your permission to download a package called “haven”. This package is built to import and export data from several types. The following window will then appear (Figure 1.14).</p>
<div class="figure" style="text-align: center"><span id="fig:fig14"></span>
<img src="images/fig1.14.png" alt="Window to install the haven package" width="90%" />
<p class="caption">
Figure 1.14: Window to install the haven package
</p>
</div>
<p>Click Yes and the download will start from the CRAN website. After the package is installed a new window will open which is called “Import Statistical Data” (Figure 1.15).</p>
<div class="figure" style="text-align: center"><span id="fig:fig15"></span>
<img src="images/fig1.15.png" alt="The Import Statistical Data window in RStudio" width="90%" />
<p class="caption">
Figure 1.15: The Import Statistical Data window in RStudio
</p>
</div>
<p>At the top right site of the window you find the button which is called “Browse”. That button allows you to browse to your dataset on your computer. After you have opened your dataset you see a preview of your dataset in RStudio (Figure 1.16).</p>
<div class="figure" style="text-align: center"><span id="fig:fig16"></span>
<img src="images/fig1.16.png" alt="A preview of the dataset in RStudio" width="90%" />
<p class="caption">
Figure 1.16: A preview of the dataset in RStudio
</p>
</div>
<p>Under Code Preview, under in the window, you see the code that was used by RStudio to read in the dataset:</p>
<p>The dataset is automatically assigned to the object: Backpain50, which is the original name of the dataset. When you click on Import, the dataset is imported in the RStudio environment (Figure 1.17).</p>
<div class="figure" style="text-align: center"><span id="fig:fig17"></span>
<img src="images/fig1.17.png" alt="Imported dataset in RStudio" width="90%" />
<p class="caption">
Figure 1.17: Imported dataset in RStudio
</p>
</div>
<p>Another way to import an SPSS dataset is by making use of the foreign package. You can find this package under the Packages Tab in the window at the right site below under the heading “System Library”. Install that package first. The foreign package includes the function “read.spss”. Let’s first explore the function arguments of this function by using:</p>
<p>Now the following information can be found in the right window below, under the Help tab:</p>
<p>read.spss(file, use.value.labels = TRUE, to.data.frame = FALSE, max.value.labels = Inf, trim.factor.names = FALSE, trim_values = TRUE, reencode = NA, use.missings = to.data.frame)</p>
<p>The most important arguments to change for us are the file and to.data.frame arguments. When you are in the correct working directory, i.e. the working directory where the file that you want to import is stored, you use the following code to import the dataset:</p>
</div>
<div id="saving-and-reading-r-data-in-rstudio" class="section level3">
<h3><span class="header-section-number">1.7.11</span> Saving and Reading R data in RStudio</h3>
<p>Datasets can be saved and read in R using different commands.</p>
<p><em>Write.table</em> and <em>Read.table</em></p>
<p><em>Write.table</em> The write.table function can be used to write matrices and data frames (datasets) to the working directory. The R code is:</p>
<p>Files that have been written with write.table can be easily read in, in SPSS by using the steps that will be discussed in the next paragraph.</p>
<p><em>Read.table</em> The read.table function can be used to read in matrices and data frames by using:</p>
<p><em>Save and Load</em></p>
<p><em>Save</em> You can also use the command save to save datasets, according to (notice the .RData extension):</p>
<p><em>Load</em> Loading the dataset again in the workspace can be done by using:</p>
<p>You can also use save by using the default options in the following way to save your datasets:</p>
<p>To get direct access to the data that you have saved, you can use the get function in combination with the load function like this:</p>
<p>With save, you can save any R object, also lists such as:</p>
<p>Subsequently, after you have removed object x from the workspace, you can load it again by using:</p>
</div>
<div id="reading-in-rstudio-data-into-spss" class="section level3">
<h3><span class="header-section-number">1.7.12</span> Reading in (R)Studio data into SPSS</h3>
<p>When you have used the write.table function to save data in R you can easily read them in into SPSS. First you have to use write.table in the following way:</p>
<p>The extra parameter settings, mean: sep=“;”, separate each variable by an “;” indicator. dec=“,”, use for decimals a “,” instead of an “.”. row.names=F , Do not add an extra column with row.names.</p>
<p>Follow the next steps to read in the data into SPSS: choose File -&gt; Open data -&gt; “All files (<em>.</em>)”, than you will see the file you want to read in into SPSS. In this example we will use the file “Backpain50 R file” from R code 1.41 (Figure 1.18).</p>
<div class="figure" style="text-align: center"><span id="fig:fig18"></span>
<img src="images/fig1.18.png" alt="Choosing the dataset to import in SPSS" width="90%" />
<p class="caption">
Figure 1.18: Choosing the dataset to import in SPSS
</p>
</div>
<p>Then click Open (wait a couple of seconds) and click on next. You will see the following window that is part of the Text Import Wizard procedure in SPSS (Figure 1.19):</p>
<div class="figure" style="text-align: center"><span id="fig:fig19"></span>
<img src="images/fig1.19.png" alt="Step 1 of the Text Import Wizard" width="90%" />
<p class="caption">
Figure 1.19: Step 1 of the Text Import Wizard
</p>
</div>
<p>Then click the “Next &gt;” button 5 times, passing by the following windows:</p>
<p>Step 2 of 6 (Figure 1.20): To change how variables are arranged: here delimited To include variable names included at the top of the file: here Yes. To set the decimal symbol: here a comma.</p>
<div class="figure" style="text-align: center"><span id="fig:fig20"></span>
<img src="images/fig1.20.png" alt="Step 2 of the Text Import Wizard" width="90%" />
<p class="caption">
Figure 1.20: Step 2 of the Text Import Wizard
</p>
</div>
<p>Step 3 of 6 (Figure 1.21):</p>
<p>On which line number begins the first case: here 2 How cases are represented: Each line is a case. How many cases you want to import: here all cases.</p>
<div class="figure" style="text-align: center"><span id="fig:fig21"></span>
<img src="images/fig1.21.png" alt="Step 3 of the Text Import Wizard" width="90%" />
<p class="caption">
Figure 1.21: Step 3 of the Text Import Wizard
</p>
</div>
<p>Step 4 of 6 (Figure 1.22): The delimiters that appear between variables; here the Semicolon. The text qualifier: here Double quote. Remove trailing spaces from string values: skip.</p>
<div class="figure" style="text-align: center"><span id="fig:fig22"></span>
<img src="images/fig1.22.png" alt="Step 4 of the Text Import Wizard" width="90%" />
<p class="caption">
Figure 1.22: Step 4 of the Text Import Wizard
</p>
</div>
<p>Step 5 of 6 (Figure 1.23): Here you can overwrite the Data format of the variable (you can also change that in the Variable View window, when the data has been read in).</p>
<div class="figure" style="text-align: center"><span id="fig:fig23"></span>
<img src="images/fig1.23.png" alt="Step 5 of the Text Import Wizard" width="90%" />
<p class="caption">
Figure 1.23: Step 5 of the Text Import Wizard
</p>
</div>
<p>Step 6 of 6: This step allows you to save your specifications of the previous steps into a separate file (Figure 1.24).</p>
<div class="figure" style="text-align: center"><span id="fig:fig24"></span>
<img src="images/fig1.24.png" alt="Step 6 of the Text Import Wizard" width="90%" />
<p class="caption">
Figure 1.24: Step 6 of the Text Import Wizard
</p>
</div>
<p>Then click finish and the data will be read in, into a new SPSS file. In that file you can of course change all kind of variable and data settings in the Variable View Window.</p>
<p>You can also skip step 2 to 5 by clicking the Finish button twice when you are at step 1. Than you use all default settings, which is most of the times a good option.</p>
</div>
<div id="installing-r-packages" class="section level3">
<h3><span class="header-section-number">1.7.13</span> Installing R Packages</h3>
<p>When R is installed on your computer also a folder called library is created. This folder contains packages that are part of the basic installation. A package is a collection of different functions written in the R language. Besides packages that are part of the basic installation of R there are also packages that are not part of the basic installation but are written by others, i.e. the add-on packages. Packages can be downloaded from the CRAN website (<a href="https://cran.r-project.org/" class="uri">https://cran.r-project.org/</a>). Currently, there are thousands of user-written packages available on the CRAN website.</p>
<p>Before you can use a specific package that is not part of the basic installation, you have to install it in your R library. In this manual we will use the mice package to do all kind of imputation procedures, such as multiple imputation. mice is not part of the basic installation so we have to install it first. There are several procedures in RStudio to install a package. One way is to use the install.packages function in the Console window as follows:</p>
<p>The mice package will be automatically downloaded from the CRAN website.</p>
<p>Another way is to use the window on the right site below and go to the Packages tab. When you click “Install” a new window is opened. Than you can type “mice” on the blank line under “Packages (separate multiple with space or comma):” (Figure 1.25a and b).</p>
<div class="figure" style="text-align: center"><span id="fig:fig25a"></span>
<img src="images/fig1.25a.png" alt="Install packages Window in RStudio to install packages from the CRAN website" width="90%" />
<p class="caption">
Figure 1.25: Install packages Window in RStudio to install packages from the CRAN website
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:fig25b"></span>
<img src="images/fig1.25b.png" alt="Enlarged Install packages Window in RStudio to install packages from the CRAN website" width="90%" />
<p class="caption">
Figure 1.26: Enlarged Install packages Window in RStudio to install packages from the CRAN website
</p>
</div>
<p>After you have clicked on “Install” the package will be downloaded from the CRAN website automatically and will be listed in the Package list named “User Library”.</p>
<p>Another way is to go to the CRAN website and download the package as a zip file in a directory on your computer, for example your working directory or in your library. Again use the window on the right site below and go to the Packages tab. When you choose Install a new window is opened. Now under “Install from:” choose for “Package Archive File (.zip; .tar.gz)” (Figure 1.26a and 1.26b). Than you can browse to the zip file and install the package.</p>
<div class="figure" style="text-align: center"><span id="fig:fig26a"></span>
<img src="images/fig1.26a.png" alt="Install packages Window in RStudio to install packages from zip files" width="90%" />
<p class="caption">
Figure 1.27: Install packages Window in RStudio to install packages from zip files
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:fig26b"></span>
<img src="images/fig1.26b.png" alt="Enlarged Install packages Window in RStudio to install packages from zip files" width="90%" />
<p class="caption">
Figure 1.28: Enlarged Install packages Window in RStudio to install packages from zip files
</p>
</div>
</div>
<div id="loading-r-packages" class="section level3">
<h3><span class="header-section-number">1.7.14</span> Loading R Packages</h3>
<p>Once an add-on (user written) R package has been installed it has to be loaded to get access to all functions that are part of that package. To load a library, you can use the function library() or require(). R code 1.43 shows an example of loading the mice package.</p>
<p>The require() function is used in the same way. You have to load add-on packages each time you start a new R session.</p>
</div>
<div id="updating-r-packages" class="section level3">
<h3><span class="header-section-number">1.7.15</span> Updating R Packages</h3>
<p>To keep the add-on packages up to date you can use the update.packages() function in R. R code 1.44 presents an example.</p>
<p>R will ask you if you want to update each package. If you type “y” in the Console window, R will update the package.</p>
<p>In RStudio updating packages can be done in the Package tab as well. You can click on the Update button. A new window will open that contains a list of all packages that need to be updated. Subsequently you can select the packages you want to update.</p>
</div>
<div id="useful-missing-data-packages-and-links" class="section level3">
<h3><span class="header-section-number">1.7.16</span> Useful Missing data Packages and links</h3>
<p>The main package that we will use in this manual is mice which stand for Multivariate Imputation by Chained Equations (MICE) (Van Buuren, 2009).</p>
<p>Other packages that are related to MICE are miceadds and micemd: miceadds: this package contains some additional multiple imputation functions (Robitzsch et al., 2017). See for more information: <a href="https://cran.r-project.org/web/packages/miceadds/index.html">linked phrase</a></p>
<p>micemd: this package contains additional functions for the mice package to perform multiple imputation in two-level (Multilevel) data (Audigier &amp; Resche-Rigon, 2017). See for more information: <a href="https://cran.r-project.org/web/packages/micemd/index.html">linked phrase</a></p>
<p>mi: provides functions for data manipulation, imputing missing values in an approximate Bayesian framework, diagnostics of the models used to generate the imputations, confidence-building mechanisms to validate some of the assumptions of the imputation algorithm, and functions to analyze multiply imputed data sets (Gelman et al., 2015). See for more information: <a href="https://cran.r-project.org/web/packages/mi/index.html">linked phrase</a></p>
<p>MItools: small package to perform analyses and combine results from multiple-imputation datasets (Lumley, 2015). See for more information: <a href="https://cran.r-project.org/web/packages/mitools/index.html">linked phrase</a></p>
<p>norm: this package is for the Analysis of multivariate normal datasets with missing values. It contains the mi.inference function. This function combines estimates and standard errors to produce a single inference. Uses the technique described by Rubin (1987), which are called the Rubin’s Rules (RR) (Novo, 2015). See for more information: <a href="https://cran.r-project.org/web/packages/norm/index.html">linked phrase</a></p>
<p>vim (visualization and imputation of missing values): This package includes tools for the visualization of missing and/or imputed values. In addition, the quality of imputation can be visually explored using various univariate, bivariate, multiple and multivariate plot methods (Templ et al., 2017). See for more information: <a href="https://cran.r-project.org/web/packages/mi/index.html">linked phrase</a></p>
<p>BaylorEdPsych: R Package for Baylor University Educational Psychology Quantitative Courses. This package included Little’s MCAR test (Beaujean, 2015). See for more information: <a href="https://cran.r-project.org/web/packages/BaylorEdPsych/index.html">linked phrase</a></p>
<p>MKmisc: Contains several functions for statistical data analysis; e.g. for sample size and power calculations, computation of confidence intervals, and generation of similarity matrices. This package contains the mi.t.test function for pooling t-tests after multiple imputation (Kohl, 2016). See for more information: <a href="https://cran.r-project.org/web/packages/MKmisc/index.html">linked phrase</a></p>
<p>mvnmle: This package estimates the maximum likelihood estimate of the mean vector and variance-covariance matrix for multivariate normal data with missing values. This package is needed for the mlest function this is used for Little’s MCAR test in Cahpter 2. See for more information: <a href="https://cran.r-project.org/web/packages/mvnmle/index.html">linked phrase</a></p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": ["Book_MI.pdf", "Book_MI.epub"],
"toc": {
"collapse": "subsection"
},
"split_by": "section"
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
